## Set Up Environment

#### Imports

In [1]:
# import libraries
from __future__ import annotations
import matplotlib.pyplot as plt
from typing import Iterable
from pathlib import Path
import seaborn as sns
import pandas as pd
import polars as pl
import numpy as np
import random
import os

#### Load Clean Folds

#### Quick Exploration

In [101]:
for col in df_clean.columns:
    display(df_clean[col].value_counts())

race
Caucasian          53491
AfricanAmerican    12887
Unknown             1948
Hispanic            1517
Other               1178
Asian                497
Name: count, dtype: int64

gender
Female     38025
Male       33490
Unknown        3
Name: count, dtype: int64

age
[70-80)     18210
[60-70)     15960
[50-60)     12466
[80-90)     11589
[40-50)      6878
[30-40)      2699
[90-100)     1900
[20-30)      1127
[10-20)       535
[0-10)        154
Name: count, dtype: int64

weight
Unknown      68665
[75-100)      1195
[50-75)        781
[100-125)      566
[125-150)      131
[25-50)         89
[0-25)          46
[150-175)       33
[175-200)        9
>200             3
Name: count, dtype: int64

admission_type_id
1    36490
3    13917
2    13028
6     4588
5     3174
8      291
7       21
4        9
Name: count, dtype: int64

discharge_disposition_id
1     44317
3      8784
6      8289
18     2474
2      1539
22     1410
11     1077
5       913
25      778
4       541
7       409
23      260
13      243
14      218
28       90
8        73
15       40
24       25
9         9
17        8
10        6
19        6
27        3
16        3
12        2
20        1
Name: count, dtype: int64

admission_source_id
7     38290
1     22007
17     4949
4      2583
6      1801
2       926
5       545
20      155
3       138
9        95
8        12
10        7
22        4
14        2
25        2
11        1
13        1
Name: count, dtype: int64

time_in_hospital
3     12701
2     12397
1     10717
4      9567
5      6839
6      5171
7      3999
8      2919
9      1990
10     1558
11     1241
12      955
13      795
14      669
Name: count, dtype: int64

payer_code
Unknown    31043
MC         20414
HM          4022
BC          3432
SP          3347
MD          2197
CP          1986
UN          1879
CM          1334
OG           658
PO           463
DM           374
CH           117
WC           117
OT            65
SI            37
MP            32
FR             1
Name: count, dtype: int64

medical_specialty
Unknown                             34477
InternalMedicine                    10919
Family/GeneralPractice               5118
Emergency/Trauma                     4465
Cardiology                           4266
                                    ...
SportsMedicine                          1
Dermatology                             1
Proctology                              1
Surgery-PlasticwithinHeadandNeck        1
Resident                                1
Name: count, Length: 71, dtype: int64

num_lab_procedures
1      2285
43     1904
44     1661
45     1621
46     1541
       ...
132       1
121       1
107       1
120       1
118       1
Name: count, Length: 116, dtype: int64

num_procedures
0    31430
1    14303
2     9150
3     7183
6     3956
4     3056
5     2440
Name: count, dtype: int64

num_medications
13    4332
12    4321
11    4080
15    3954
14    3915
      ...
75       2
72       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64

number_outpatient
0     62212
1      4867
2      2025
3      1116
4       585
5       288
6       128
7        73
8        57
9        37
10       28
11       19
12       14
13       13
14       10
15       10
16        8
17        4
20        4
27        2
33        2
24        2
22        2
18        2
21        2
19        1
29        1
42        1
36        1
26        1
35        1
25        1
23        1
Name: count, dtype: int64

number_emergency
0     66314
1      3965
2       804
3       246
4        96
5        33
6        26
8         9
7         8
10        5
9         4
11        2
13        1
42        1
25        1
37        1
20        1
16        1
Name: count, dtype: int64

number_inpatient
0     63077
1      5962
2      1547
3       489
4       236
5       102
6        56
7        19
8        13
9         8
10        5
11        2
12        2
Name: count, dtype: int64

diag_1
414       5233
428       3980
786       3040
410       2902
486       2439
          ...
848          1
250.51       1
691          1
834          1
V51          1
Name: count, Length: 697, dtype: int64

diag_2
250     5009
276     4604
428     4335
427     3539
401     3088
        ...
704        1
911        1
520        1
E890       1
927        1
Name: count, Length: 726, dtype: int64

diag_3
250     9039
401     6588
276     3448
428     2847
427     2707
        ...
853        1
E882       1
395        1
E822       1
971        1
Name: count, Length: 759, dtype: int64

number_diagnoses
9     31740
5      8941
6      7691
7      7609
8      7560
4      4464
3      2364
2       881
1       193
16       31
13       10
10        9
12        7
15        7
11        6
14        5
Name: count, dtype: int64

max_glu_serum
Not Measured    68062
Norm             1731
>200              969
>300              756
Name: count, dtype: int64

A1Cresult
Not Measured    58532
>8               6304
Norm             3791
>7               2891
Name: count, dtype: int64

metformin
No        56527
Steady    13718
Up          838
Down        435
Name: count, dtype: int64

repaglinide
No        70592
Steady      824
Up           73
Down         29
Name: count, dtype: int64

nateglinide
No        71020
Steady      474
Up           16
Down          8
Name: count, dtype: int64

chlorpropamide
No        71446
Steady       67
Up            4
Down          1
Name: count, dtype: int64

glimepiride
No        67773
Steady     3372
Up          235
Down        138
Name: count, dtype: int64

acetohexamide
No        71517
Steady        1
Name: count, dtype: int64

glipizide
No        62412
Steady     8150
Up          578
Down        378
Name: count, dtype: int64

glyburide
No        63664
Steady     6812
Up          621
Down        421
Name: count, dtype: int64

tolbutamide
No        71499
Steady       19
Name: count, dtype: int64

pioglitazone
No        66210
Steady     5047
Up          180
Down         81
Name: count, dtype: int64

rosiglitazone
No        66817
Steady     4490
Up          136
Down         75
Name: count, dtype: int64

acarbose
No        71316
Steady      192
Up           10
Name: count, dtype: int64

miglitol
No        71498
Steady       18
Down          1
Up            1
Name: count, dtype: int64

troglitazone
No        71515
Steady        3
Name: count, dtype: int64

tolazamide
No        71488
Steady       30
Name: count, dtype: int64

examide
No    71518
Name: count, dtype: int64

citoglipton
No    71518
Name: count, dtype: int64

insulin
No        34921
Steady    22129
Down       7505
Up         6963
Name: count, dtype: int64

glyburide-metformin
No        71016
Steady      491
Up            7
Down          4
Name: count, dtype: int64

glipizide-metformin
No        71511
Steady        7
Name: count, dtype: int64

glimepiride-pioglitazone
No    71518
Name: count, dtype: int64

metformin-rosiglitazone
No        71516
Steady        2
Name: count, dtype: int64

metformin-pioglitazone
No        71517
Steady        1
Name: count, dtype: int64

change
No    39494
Ch    32024
Name: count, dtype: int64

diabetesMed
Yes    54319
No     17199
Name: count, dtype: int64

readmitted_30_days
0    65225
1     6293
Name: count, dtype: int64

#### Configuration for Reduction

In [102]:
# medication columns
MEDICATION_COLUMNS = [
    "metformin",
    "repaglinide",
    "nateglinide",
    "chlorpropamide",
    "glimepiride",
    "acetohexamide",
    "glipizide",
    "glyburide",
    "tolbutamide",
    "pioglitazone",
    "rosiglitazone",
    "acarbose",
    "miglitol",
    "troglitazone",
    "tolazamide",
    "examide",
    "citoglipton",
    "insulin",
    "glyburide-metformin",
    "glipizide-metformin",
    "glimepiride-pioglitazone",
    "metformin-rosiglitazone",
    "metformin-pioglitazone"
]

# purity threshold for concern
PURITY_THRESHOLD = 98
DROP_THRESHOLD = 100

#### Explore Feature Label Imbalance

In [103]:
def calculate_column_purity(dataset: pd.DataFrame) -> pd.DataFrame:
    """
    compute purity, defined as percent of values taken up by modal label
    """
    purity_results = []
    total_rows = len(dataset)
    for column in dataset.columns:
        value_counts = dataset[column].value_counts()

        # determine model value and count
        most_common_value = value_counts.index[0]
        most_common_count = value_counts.iloc[0]

        # calculate percentage of values taken up by mode
        purity_percentage = (
            most_common_count / total_rows
        ) * 100

        # save results
        purity_results.append(
            {
                "column": column,
                "most_common_value": most_common_value,
                "most_common_count": most_common_count,
                "purity_percentage": purity_percentage,
                "unique_values": dataset[column].nunique(),
            }
        )

    # aggregate results and sort
    purity_summary = pd.DataFrame(
        purity_results
    ).sort_values(
        "purity_percentage",
        ascending=False,
    )

    return purity_summary.reset_index(drop=True)

# calculate purity
column_purity_summary = calculate_column_purity(df_clean)
display(column_purity_summary.query(f'purity_percentage >= {PURITY_THRESHOLD}'))

,column,most_common_value,most_common_count,purity_percentage,unique_values
0,glimepiride-pioglitazone,No,71518,100.000000,1
1,citoglipton,No,71518,100.000000,1
2,examide,No,71518,100.000000,1
3,metformin-pioglitazone,No,71517,99.998602,2
4,acetohexamide,No,71517,99.998602,2
5,metformin-rosiglitazone,No,71516,99.997204,2
6,troglitazone,No,71515,99.995805,2
7,glipizide-metformin,No,71511,99.990212,2
8,tolbutamide,No,71499,99.973433,2
9,miglitol,No,71498,99.972035,4
10,tolazamide,No,71488,99.958053,2
11,chlorpropamide,No,71446,99.899326,4
12,acarbose,No,71316,99.717554,3
13,nateglinide,No,71020,99.303672,4
14,glyburide-metformin,No,71016,99.298079,4
15,repaglinide,No,70592,98.705221,4

In [104]:
# break down by medication
column_purity_summary.loc[column_purity_summary['column'].isin(MEDICATION_COLUMNS)]

,column,most_common_value,most_common_count,purity_percentage,unique_values
0,glimepiride-pioglitazone,No,71518,100.000000,1
1,citoglipton,No,71518,100.000000,1
2,examide,No,71518,100.000000,1
3,metformin-pioglitazone,No,71517,99.998602,2
4,acetohexamide,No,71517,99.998602,2
5,metformin-rosiglitazone,No,71516,99.997204,2
6,troglitazone,No,71515,99.995805,2
7,glipizide-metformin,No,71511,99.990212,2
8,tolbutamide,No,71499,99.973433,2
9,miglitol,No,71498,99.972035,4
10,tolazamide,No,71488,99.958053,2
11,chlorpropamide,No,71446,99.899326,4
12,acarbose,No,71316,99.717554,3
13,nateglinide,No,71020,99.303672,4
14,glyburide-metformin,No,71016,99.298079,4
15,repaglinide,No,70592,98.705221,4
18,glimepiride,No,67773,94.763556,4
19,rosiglitazone,No,66817,93.426830,4
21,pioglitazone,No,66210,92.578092,4
23,glyburide,No,63664,89.018149,4
25,glipizide,No,62412,87.267541,4
28,metformin,No,56527,79.038843,4
36,insulin,No,34921,48.828267,4

#### Drop Pure Labelled Columns

In [105]:
# drop the uninformation columns
pure_columns = list(column_purity_summary
                    .loc[column_purity_summary['purity_percentage']
                         >=DROP_THRESHOLD]
                    ['column'].values)
df_reduced = df_clean.drop(columns=pure_columns)

In [106]:
# extend to folds
def reduce_df(df_clean):
    # calculate purity
    column_purity_summary = calculate_column_purity(df_clean)
    pure_columns = list(column_purity_summary
                    .loc[column_purity_summary['purity_percentage']
                         >=DROP_THRESHOLD]
                    ['column'].values)
    df_reduced = df_clean.drop(columns=pure_columns)
    return df_reduced

folds_df_reduced = folds_functions(folds_df_clean, [reduce_df])

## Feature Encoding and Mapping

#### Configuration for Encodings

In [107]:
# ids to map to look up table
LOOKUP_COLUMNS = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']

# admission type id map
ADMISSION_TYPE_MAP = {
    1: "Emergency",
    2: "Urgent",
    3: "Elective",
    4: "Newborn",
    5: "Not Available",
    6: "NULL",
    7: "Trauma Center",
    8: "Not Mapped"
}

# discharge disposition id map
DISCHARGE_DISPOSITION_MAP = {
    1: "Discharged to home",
    2: "Transferred to another short term hospital",
    3: "Transferred to skilled nursing facility",
    4: "Transferred to intermediate care facility",
    5: "Transferred to another inpatient institution",
    6: "Discharged to home with home health service",
    7: "Left against medical advice",
    8: "Home under care of IV provider",
    9: "Admitted as inpatient to this hospital",
    10: "Neonate discharged to another hospital",
    11: "Expired",
    12: "Still patient or expected to return",
    13: "Hospice / home",
    14: "Hospice / medical facility",
    15: "Transferred within institution",
    16: "Transferred outpatient",
    17: "Transferred rehab facility",
    18: "NULL",
    19: "Expired at home",
    20: "Expired in medical facility",
    21: "Expired, unknown place",
    22: "Transferred psychiatric hospital",
    23: "Transferred long-term care",
    24: "Medicaid only hospice",
    25: "Not Mapped",
    26: "Unknown/Invalid"
}

# admission source id map
ADMISSION_SOURCE_MAP = {
    1: "Physician Referral",
    2: "Clinic Referral",
    3: "HMO Referral",
    4: "Transfer from hospital",
    5: "Transfer from skilled nursing facility",
    6: "Transfer from another health care facility",
    7: "Emergency Room",
    8: "Court/Law Enforcement",
    9: "Not Available",
    10: "Transfer from critical access hospital",
    11: "Normal Delivery",
    12: "Premature Delivery",
    13: "Sick Baby",
    14: "Extramural Birth",
    15: "Not Available",
    17: "NULL",
    18: "Transfer from another home health agency",
    19: "Readmission to same home health agency",
    20: "Not Mapped",
    21: "Unknown/Invalid",
    22: "Transfer from hospital inpatient/same facility",
    23: "Born inside this hospital",
    24: "Born outside this hospital",
    25: "Transfer from ambulatory surgery center",
    26: "Transfer from hospice"
}

'''
# omitted as descriptors too long
df["admission_type"] = df["admission_type_id"].map(ADMISSION_TYPE_MAP)
df["discharge_disposition"] = df["discharge_disposition_id"].map(DISCHARGE_DISPOSITION_MAP)
df["admission_source"] = df["admission_source_id"].map(ADMISSION_SOURCE_MAP)

# also in IDS_mapping.csv
# https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008
'''

'\n# omitted as descriptors too long\ndf["admission_type"] = df["admission_type_id"].map(ADMISSION_TYPE_MAP)\ndf["discharge_disposition"] = df["discharge_disposition_id"].map(DISCHARGE_DISPOSITION_MAP)\ndf["admission_source"] = df["admission_source_id"].map(ADMISSION_SOURCE_MAP)\n\n# also in IDS_mapping.csv\n# https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008\n'

In [108]:
# ordinal columns and mappings
ORDINAL_COLUMNS = ['age', 'weight']
AGE_COLUMN = 'age'
WEIGHT_COLUMN = 'weight'

# for age encode mid point
AGE_MAPPING = {
    "[0-10)": 5,
    "[10-20)": 15,
    "[20-30)": 25,
    "[30-40)": 35,
    "[40-50)": 45,
    "[50-60)": 55,
    "[60-70)": 65,
    "[70-80)": 75,
    "[80-90)": 85,
    "[90-100)": 95,
}

# for weight encode mid point
# end points likely limited
WEIGHT_MAPPING = {
    "[0-25)": 12.5,
    "[25-50)": 37.5,
    "[50-75)": 62.5,
    "[75-100)": 87.5,
    "[100-125)": 112.5,
    "[125-150)": 137.5,
    "[150-175)": 162.5,
    "[175-200)": 187.5,
    ">200": 212.5, # project linearly
    UNKNOWN: UNKNOWN, # keep untouched since too common
}

In [109]:
# nominal columns to flatten
ONE_HOT_COLUMNS = [
    "race",
    "gender",
    "age",
    "weight",
    "admission_type_id",
    "admission_source_id",
    "discharge_disposition_id",
    "payer_code",
    "max_glu_serum",
    "A1Cresult",
    "change",
    "diabetesMed"
] + MEDICATION_COLUMNS

# decide which columns to one hot encode
# df_reduced.nunique()

#### Ordinal Encoding

In [110]:
def ordinal_encode(df_reduced):
    # create ordinally encoded numeric features using mid points
    df_reduced["age"] = (
        df_reduced[AGE_COLUMN]
        .map(AGE_MAPPING)
    )
    df_reduced["weight"] = (
        df_reduced[WEIGHT_COLUMN]
        .map(WEIGHT_MAPPING)
    )
    return df_reduced

#### One Hot Encoding

In [111]:
def one_hot_encode(df_reduced):
    # limit columns
    SAFE_ONE_HOT_COLUMNS = [col for col in ONE_HOT_COLUMNS 
                            if col in df_reduced.columns]
    # One-hot encode
    df_encoded = pd.get_dummies(
        df_reduced,
        columns=SAFE_ONE_HOT_COLUMNS,
        # drop_first=True # toggle this to avoid multicollinearity
        # but should try keep it deterministic regardless of column presence
    )

    # convert booleans to integers
    bool_cols = df_encoded.select_dtypes(include="bool").columns
    df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)
    return df_encoded

In [112]:
# check result
#print(df_encoded.shape)
#display(df_encoded.head())

#### Extend to folds

In [113]:
folds_df_encoded = folds_functions(folds_df_reduced, [ordinal_encode, one_hot_encode])